export let plantaosexta = [
    { data: new Date(2025, 2, 28), person: "Andressa", monitoria: "Douglas e Rose" },
    { data: new Date(2025, 3, 4), person: "Jaque", monitoria: "Kadu e Eliane" },
    { data: new Date(2025, 3, 11), person: "Renata", monitoria: "Daniel e Lucia" },
    { data: new Date(2025, 3, 25), person: "Camila", monitoria: "Wesley e Yasmille" },
    { data: new Date(2025, 4, 9), person: "Valeria", monitoria: "Henrique e Rose" },
    { data: new Date(2025, 4, 16), person: "Carin", monitoria: "Douglas e Eliane" },
    { data: new Date(2025, 4, 23), person: "Josi", monitoria: "Kadu e Lucia" },
    { data: new Date(2025, 4, 30), person: "Alícia", monitoria: "Daniel e Carmelis" },
    { data: new Date(2025, 5, 6), person: "Nailson", monitoria: "Christian e Yasmille" },
    { data: new Date(2025, 5, 13), person: "Diretor", monitoria: "Wesley e Rose" },
    { data: new Date(2025, 5, 20), person: "Feriado", monitoria: "Feriado" },
    { data: new Date(2025, 5, 27), person: "Vinícius", monitoria: "Douglas e Lucia" },
    { data: new Date(2025, 6, 4), person: "Carol", monitoria: "Daniel e Patrícia" },
    { data: new Date(2025, 6, 25), person: "Murilo", monitoria: "" },
    { data: new Date(2025, 7, 1), person: "Carol", monitoria: "" },
    { data: new Date(2025, 7, 8), person: "Renata", monitoria: "" },
    { data: new Date(2025, 7, 15), person: "Andressa", monitoria: "" },
    { data: new Date(2025, 7, 22), person: "Jaque", monitoria: "" },
    { data: new Date(2025, 7, 29), person: "Malu", monitoria: "" },
    { data: new Date(2025, 8, 5), person: "Camila", monitoria: "" },
    { data: new Date(2025, 8, 12), person: "Valéria", monitoria: "" },
    { data: new Date(2025, 8, 19), person: "Carin", monitoria: "" },
    { data: new Date(2025, 8, 26), person: "Josi", monitoria: "" },
    { data: new Date(2025, 9, 3), person: "Rocha", monitoria: "" },
    { data: new Date(2025, 9, 10), person: "Douglas", monitoria: "" },
    { data: new Date(2025, 9, 17), person: "Alícia", monitoria: "" },
    { data: new Date(2025, 9, 24), person: "Vinícius", monitoria: "" },
    { data: new Date(2025, 9, 31), person: "Leonardo", monitoria: "" },
    { data: new Date(2025, 10, 7), person: "Murilo", monitoria: "" },
    { data: new Date(2025, 10, 14), person: "Rocha", monitoria: "" },
    { data: new Date(2025, 10, 21), person: "Douglas", monitoria: "" },
    { data: new Date(2025, 10, 28), person: "Vinícius", monitoria: "" },
    { data: new Date(2025, 11, 5), person: "Leonardo", monitoria: "" },
    { data: new Date(2025, 12, 12), person: "Murilo", monitoria: "" }
];